[platformio]
;default_envs = esp32c3
default_envs = esp32dev

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.35.8
    bblanchon/ArduinoJson@^7.0.4
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git

;[env:esp32c3]
;board = esp32-c3-devkitm-1
;build_flags = 
;    -D ESP32_C3_BOARD
;    -D ARDUINO_USB_MODE=1
;    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:esp32dev]
board = esp32dev
build_flags = 
    -D ESP32_CLASSIC_BOARD